config/routes.rb
# Rails.application.routes.draw do
#   devise_for :users

#   root to: "users#index"
#   resources :users, only: [:index, :show] do
#     resources :posts, only: [:index, :show, :new, :create, :destroy] do
#       post "new_comment", to: "comments#create", on: :member
#       post "like_post", to: "likes#create", on: :member
#       post "like_post", to: "likes#create", on: :member
#     end
#   end

#   resources :comments, only: [:destroy]
# end

Rails.application.routes.draw do
  devise_for :users
  root to: "users#index"
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      post "new_comment", to: "comments#create", on: :member
      post "like_post", to: "likes#create", on: :member
    end
  end

  resources :comments, only: [:destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    if user.nil? # Insted of `user ||= User.new` # guest user (not logged in)
      can :read, :all
      return
    end

    if user.admin?
      can :destroy, Post
      can :destroy, Comment
    end

    can :read, :all
    can :manage, Post, author_id: user.id
    can :manage, Comment, author_id: user.id
    can :manage, Comment, post: { author_id: user.id }
    can :manage, Like, author_id: user.id
    can :create, Comment
    can :create, Like

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_comments_counter

  def recent_comments
    comments.order('created_at Des').limit(5)
  end

  private

  def update_posts_counter
    post.decrement!(:comments_counter)
  end

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes
  after_save :update_posts_counter

  def recent_comments
    comments.order('created_at DESC').limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end

  def update_posts_counter_after_destroy
    user.decrement!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #  :confirmable
  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  def fetch_recent_posts
    posts.order('created_at DESC').limit(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #   protect_from_forgery with: :exception

  #   before_action :update_allowed_parameters, if: :devise_controller?

  #   protected

  #   def update_allowed_parameters
  #     devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  #     devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  #   end
  # end

  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?
  def after_sign_out_path_for(_resource_or_scope)
    user_session_path
  end

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :posts_counter, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :posts_counter, :email,
               :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def create
    post = Post.find(params[:id])
    comment = post.comments.create(comment_params)
    comment.author_id = current_user.id
    comment.save
    if comment.save
      flash[:success] = 'Your comment was created'
      redirect_to user_post_path(post.author_id, post.id)
    else
      flash[:error] = 'Your comment was not added'
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    flash[:success] = 'Your comment was deleted'
    redirect_to root_url
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
# class LikesController < ApplicationController
#   load_and_authorize_resource

#   def create
#     @post = Post.find(params[:post_id])
#     new_like = current_user.likes.new(
#       author_id: current_user.id,
#       post_id: @post.id
#     )
#     if new_like.save
#       redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", flash: { alert: 'Your like is saved' }
#     else
#       redirect_to "/users/#{@post.author_id}/posts/#{@post.id}", flash.now[:error] = 'Could not save like'
#     end
#   end
# end

class LikesController < ApplicationController
  load_and_authorize_resource

  def create
    post = Post.find(params[:id])
    like = current_user.likes.create(post:)
    if like.save!
      flash[:success] = 'like added'
    else
      flash[:error] = 'like was not added'
    end
    redirect_to user_post_path(@post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = User.find(params[:user_id]).posts.includes(:comments).find(params[:id])
    authorize! :read, @post
  end

  def new
    @user = User.find(params[:user_id])
    @post = @user.posts.new
    render :new, locals: { post: @post }
  end

  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.new(post_params)
    if @post.save
      flash[:success] = 'Post created successfully'
      redirect_to user_posts_url
    else
      render :new, locals: { post: @post }
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy
    authorize! :read, @post

    flash[:success] = 'Post deleted successfully'
    redirect_to user_posts_url
  end

  private

  def post_params
    params.require(:post).permit(:author_id, :title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%
=begin%>
 <h1>Add Comment</h1>
<%= form_with model: @post, url: user_posts_path, method: :post, local: true, scope: :new_post, class: "form" do |form| %>
  <div class="mb-3">
    <%= form.label :post_title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="mb-3">
    <%= form.label :your_post %>
    <%= form.text_area :text, class: "form-control text" %>
  </div>
  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %> 
<%
=end%>

app/views/common/_header.html.erb
<header>
  <div>
    <%= link_to image_tag(""), root_path %>
  </div>
  <div>
      <form>
        <input type="search" placeholder="search"/>
        <div>
          <button type="submit">Search</button>
        </div>
      </form>
  </div>
</header>

app/views/common/_post.html.erb
<div class="px">
<%= link_to user_post_path(post.author, post) do %>
  <li>
    <h5>Post #<%= "#{post.id}" %> <%= post.title %></h5>
    <p><%= post.text[0..200] ... %></p>
    <p> 
      <small>Comments: <%= post.comments_counter || 0 %>, </small>
      <small> Likes: <%= post.likes_counter || 0 %></small>
    </p>
    <% if can? :destroy, post %>
      <%= button_to 'Delete Post' , user_post_path(@user, post), method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </li>
<% end %>
</div>

app/views/common/_user.html.erb
<li>
  <div>
    <%= image_tag "#{user.photo}", width:'100vw', height:'100%', class: "all-border mx-auto w-100"%>
  </div>
  <%= link_to(user) do %>
    <div>
      <div class="all-border p-2 my-2">
          <h2><%= user.name %></h2>
          <p>Number of posts:<%= user.posts_counter || 0 %></p>
      </div>
      <% if current_page?(users_path) || current_page?(root_path)%>
        <p><%= user.bio[0..150]... %></p>
      <% end %> 
      <div>
        <% if current_page?(users_path) || current_page?(root_path)%>
          <%= link_to 'View User', user %>
        <% end %>
      </div>
    </div>
  <% end %>
</li>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="d-flex">
    <%= link_to "Blog App", root_path, id: "logo" %>
 <nav>
      <ul class="d-flex nav-list gap-10">
        <% if user_signed_in? %>
          <li><%= link_to "Home  |", root_path %></li>
          <li><%= link_to "New post  |"%></li>
          <li><%= link_to "All posts  |" %></li>
          <li><%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "logout"%></li>
        <%end%>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <div>
      <%= render 'layouts/header' %>
      <p class="notice d-flex align-items-center justify-content-center"><%= notice %></p>
      <p class="alert d-flex align-items-center justify-content-center"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_creation_of_comments.html.erb
<div class="p-5 w-75 mx-auto bg-color">
<%= form_with url: new_comment_user_post_path, scope: :comment do |form| %>
<div class="p-5">
	<%= form.text_area :text, placeholder: "Type something here...", rows: 14, required: true, class: "w-100" %>
  </div>
	<div class="w-25 mx-auto pb-3">
	  <button>
	    <%= form.submit "Comment", class: "comment-btn" %>
	  </button>
	</div>
<% end %>
</div>

app/views/posts/_delete_comment.html.erb
<%
=begin%>
 <% unless current_user.nil? || cannot?(:destroy, comment) %>
  <%= form_with url: '/comments/delete', method: :delete do |form| %>
    <%= form.hidden_field :comment_id, value: comment.id %>
    <%= button_to 'Delete', '#', onclick: 'Rails.fire(this.parentNode, \'submit\')' %>
  <% end %>
<% end %> 
<%
=end%>

<%= button_to 'Delete Post' , user_posts_path(@user, post), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/posts/_delete_post.html.erb
<% unless current_user.nil? || cannot?(:destroy, post) %>
  <%= form_with url: url, method: :delete do |form| %>
    <%= form.hidden_field :post_id, value: post.id %>
    <%= form.hidden_field :url, value: request.url %>
    <%= button_to 'Delete', '#', onclick: 'Rails.fire(this.parentNode, \'submit\')' %>
  <% end %>
<% end %>

app/views/posts/index.html.erb
  <div class="p-5 bg-color w-25 mx-auto">
  <div>
    <div>
      <h2><%= @user.name%></h2>
      <p>Number of posts: <%= @user.posts_counter %></p>
    </div>
  </div>

<% @posts.each do |post| %>
  <div>
    <div>
     <%= link_to "#{post.title}", user_post_path(@user.id, post.id), class:"anything" %> 
      <h3><%= post.text%></h3>
      <p>Number of comments: <%= post.comments_counter %> <span>Number of likes: <%= post.likes_counter %></span></p>
    </div>
  </div>
  <div>
    <% post.recent_comments.each do |comment| %>
       <h2><%= comment.author.name%>: <%= comment.text%></h2>
    <%end%>
  </div>
<%end%>

<div>
  <button>
      Pagination
  </button>
</div>

<% if can? :create, Post %>
  <button class="mt-2">
    <%= link_to 'Create a post', new_user_post_path(@user.id) %>
  </button>
<% end %>
</div>

app/views/posts/new.html.erb
<div class="bg-color p-5 mx-auto w-50">
  <h1 class="text-center text-color">Create a post</h1>
  <%= form_with url: users_path, scope: :data do |form| %>
  <div class="w-100 p-4">
	  <section>
		  <%= form.text_field :title, placeholder: "Title", required: true, class: "w-100 my-3" %>
	  </section>
	  <section>
		  <%= form.text_area :text, placeholder: "Type here...", rows: 14, required: true, class: "w-100" %>
	  </section>
	  <div class="mx-auto w-25">
		  <button>
	      <%= form.submit "Post", class: "post-btn" %>
			</button>
	  </div>
  </div>
<% end %>
</div>

app/views/posts/show.html.erb
<section>
<div class="all-border w-75 mx-auto">
  <div class="w-50 mx-auto p-5">
  <div class="user_data_post"> 
      <h2><%= @post.title %> by <span><%= @post.author.name %></span></h2>
    </div>
    <div class="my-3">
      <h5>Post #<%= "#{@post.id}" %> by <%= @post.author.name %></h5>
      <p> 
        <small>Comments: <%= @post.comments_counter || 0 %>, </small>
        <small> Likes: <%= @post.likes_counter || 0 %></small>
      </p>
    </div>
    <p><%= @post.text %></p>
  </div>
  <% if @post.comments != [] %>
  <div>
    <ul>
      <% @post.comments.each do |comment| %>
        <li>
          <p><%= comment.author.name %>: <%= comment.text%></p>
        </li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <div class="post-see-btns ">
  <button>
    <%= link_to 'See all posts', user_posts_path(@post.author), class: "see-all-post-btn"%>
  </button>
  <button>
  <%= form_with url: "/posts/#{@post.id}/likes", scope: :like do |form| %>
        <%= form.submit "Like this post", class: "post-like-btn"%>
      <% end %>
  </button>
  </div>
  <div>
    <%= render partial: "creation_of_comments", local: { post: @post } %>
  </div>
</div>
</section>

app/views/users/index.html.erb
<div class="user-container">
<% @users.each do |user| %>
  <div class="user">
      <div>
        <%= image_tag("image1.jpg", width:'100vw', height:'100%') %>
      </div>
      <div class="col">
        <%= link_to user_path(user.id) do %>
        <h2 class="user-name"><%= user.name%></h2>
        <% end %>
        <p>Number of posts: <%= user.posts_counter %></p>
      </div>
  </div>
<%end%>
</div>

app/views/users/show.html.erb
<section>
<div class="p-5 mx-auto bg-color w-25">
  <%= render "common/user", :user => @user %>
  <div class="all-border p-2">
    <h5>Bio</h5>
    <p><%= @user.bio %></p>
  </div>
  
  <div class="all-border p-2 my-2">
    <ul>
      <% @user.fetch_recent_posts.each do |post| %>
          <%= render 'common/post', :post => post %>
      <% end %>
    </ul>
  </div>
  <div >
    <button><%= link_to 'See all users', users_path %></button>
    <button><%= link_to 'See all posts', user_posts_path(@user.id) %></button>
  </div>
  </div>
</section>